### ISSUE TITLE
권한 확인을 인터셉터로 처리하기

### ISSUE THREAD

**Issue by yooyouny** [Siren-repo/Siren#42]
### 📄 Describe

기존 service 레이어에서 확인하던 권한확인을 인터셉터에서 처리
1. 권한확인 로직을 횡단 관심사로 분리하여 중복 코드 줄이기
2. 서비스 메소드가 단일 책임만 수행할 수 있도록 의존도 줄이기 
3. 스프링 컨텍스드 내부에서 처리하는 인터셉터 활용

### ✅ Tasks

- [x] Spring MVC에서 제공하는 인터셉터를 활용하여 권한 확인 로직 설정
- [x] 기존 서비스 메소드에서 권한 확인하는 기존 로직들을 삭제
- [x] 컨트롤러에 권한 확인 로직 추가
- [x] 관련 테스트 모두 변경
