### ISSUE TITLE
분산서버 환경으로 확장하기

### ISSUE THREAD

**Issue by yooyouny** [Siren-repo/Siren#47]
### 📄 Describe

main에 push 시 jenkins에서 docker img 생성해서 docker hub에 push 하는걸로 변경하기 
docker hub에 새 이미지가 푸시되면 운영서버에 여러 서버 띄우기
서버 앞에 로드밸런서 추가하고 트래픽 부하가 심한 서버는 피해서 연결 시도하는 방식 적용하기   

### ✅ Tasks

- [ ] docker compose 생성 및 docker img 생성 테스트 
- [ ] docker img 생성 후 docker hub로 push 하도록 jenkins 설정 변경 
- [ ] docker hub에 이미지 올라오는 경우 자동으로 서버 새로 띄우도록 변경 
- [ ] 로드밸런서 추가 
- [ ] 로드밸런서 설정
