### ISSUE TITLE
feat: 회원가입 기능 구현 

### ISSUE THREAD

**Issue by yooyouny** [Siren-repo/Siren#5]
### 📄 Describe

- 인증 JWT로 처리 
- Spring security 설정
- refresh token은 redis에 저장
- 이메일 중복체크 API, 스태프 확인 API 포함

### ✅ Tasks

- [x] UserEntity 구현
- [x] Spring security 설정
- [x] 필터 구현
- [x] 회원가입 API 개발 
- [x] 회원가입 예외처리
- [x] 회원가입 API 테스트 코드 작성
