### ISSUE TITLE
feat :  매장 관리 기능 구현

### ISSUE THREAD

**Issue by TaehoLEEKR** [Siren-repo/Siren#6]
### 📄 Describe

-  매장 등록
- 매장 정보 수정
- 매장 상세 조회
- 내 주변 매장 조회

### ✅ Tasks

- [x] #7
    - [x] StoreEntity 구현
    - [x] #8
    - [x] 매장 정보 init
- [x] 매장 정보 수정
- [x] 매장 상세 조회
- [x] 내 주변 매장 조회 
    - [x] GPS 기반 주변 위도 경도 조회
    - [x] 직접 위도 경도 조
